image: nikolaik/python-nodejs:python3.11-nodejs16
pipelines:
  branches:
    master:
      - step:
          deployment: Production
          caches:
            - node
          script:
            - yarn install
            - CI=false yarn build
            - pip install awscli --upgrade --ignore-installed six
            - aws s3 sync ./build s3://verifiedimpactnfts.com --acl bucket-owner-full-control --acl public-read
    staging:
      - step:
          deployment: Production
          caches:
            - node
          script:
            - yarn install
            - CI=false yarn build
            - pip install awscli --upgrade --ignore-installed six
            - aws s3 sync ./build s3://staging.verifiedimpactnfts.com --acl bucket-owner-full-control --acl public-read
    bf-staging:
      - step:
          deployment: Staging
          caches:
            - node
          script:
            - yarn install
            - CI=false yarn build
            - pip install awscli --upgrade --ignore-installed six
            - aws s3 sync ./build s3://dev.verifiedimpactnfts.com --acl bucket-owner-full-control --acl public-read
