
import Bucha1 from './../images/Bucha1.jpg';
import Bucha2 from './../images/Bucha2.jpg';
import Bucha3 from './../images/Bucha3.jpg';
import Bucha4 from './../images/Bucha4.jpg';
import Bucha5 from './../images/Bucha5.jpg';
import Bucha6 from './../images/Bucha6.jpg';
import Bucha7 from './../images/Bucha7.jpg';
import Bucha8 from './../images/Bucha8.jpg';
import Bucha9 from './../images/Bucha9.jpg';
import Bucha10 from './../images/Bucha10.jpg';
import Bucha11 from './../images/Bucha11.jpg';
import Bucha12 from './../images/Bucha12.jpg';

export const imageBlog = [
    {
      id: 1,
      name: "Prayer",
      image:
        "https://churchrez.org/wp-content/uploads/2022/03/Pray-for-Ukraine-IG.png",
      category: "1",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Pray for Ukraine",
      price: "1000",
      currency: "CSPR",
      description: "During hard days we should pray for peace ",
    },
    {
      id: 2,
      name: "Solidarity",
      image: "https://www.eqar.eu/assets/uploads/2022/02/Flag_of_Ukraine.jpeg",
      category: "1",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Pray for Ukraine",
      price: "1000",
      currency: "CSPR",
      description:
        "Solidarity and support to Ukraine is just a humane action regardless the consequences ",
    },
    {
      id: 3,
      name: "The Motherland Monument",
      image:
        "https://rayleighbaptist.org.uk/wp-content/uploads/2022/02/Pray-for-Ukraine.png",
      category: "1",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Pray for Ukraine",
      price: "1000",
      currency: "CSPR",
      description:
        "The Motherland Monument is a monumental statue in Kyiv, the capital of Ukraine. The sculpture is a part of the National Museum of the History of Ukraine in the Second World War.",
    },
    {
      id: 4,
      name: "The Flag",
      image:
        "https://forhiskingdomandourgood.files.wordpress.com/2022/03/pray-for.png?w=500",
      category: "1",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Pray for Ukraine",
      price: "1000",
      currency: "CSPR",
      description:
        "The colours in the Ukrainian flag represent golden fields of grain under a clear blue sky, appropriate for a country known as the 'bread basket' of its area.",
    },
    {
      id: 5,
      name: "Dove of Peace",
      image:
        "https://news.scranton.edu/articles/2022/03/images/ukraine-prayer-vigil-3-10-22.jpg",
      category: "1",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Pray for Ukraine",
      price: "1000",
      currency: "CSPR",
      description: "The Dove of peace will definitely fly over Ukrain soon ",
    },
    {
      id: 6,
      name: "No War!",
      image:
        "https://thumbs.dreamstime.com/z/destroyed-buildings-ruins-concrete-form-word-no-war-destruction-concept-illustration-242469701.jpg",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Build it Back",
      price: "1000",
      currency: "CSPR",
      description:
        "Stop war to rebuild",
    },
    { 
      id: 7,
      name: "Once Upon a Time",
      image:
        "https://i.ytimg.com/vi/yfkI2TbkW8Q/maxresdefault.jpg",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Build it Back",
      price: "1000",
      currency: "CSPR",
      description:
        "Kiev is the colourful city ",
    },
    {
      id: 8,
      name: "New City",
      image:
        "https://www.northworldindustry.com/wp-content/uploads/2018/08/construccion-servicio-800x650.jpg.webp",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Build it Back",
      price: "1000",
      currency: "CSPR",
      description: "Reconstruction of a city is simply way harder than destroying it",
    },
    {
      id: 9,
      name: "Farming",
      image:
        "https://www.arc2020.eu/wp-content/uploads/2016/04/ukraine-cereal-by-voffka.jpg",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Build it Back",
      price: "1000",
      currency: "CSPR",
      description: "We shall retain our bread basket city!",
    },
    {
      id: 10,
      name: "Stop War",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Fists+Maidan+Nezalezhnosti+Central+Square+Capital+City+Ukraine.png.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 11,
      name: "Stop War 1",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Flag+Maidan+Nezalezhnosti+Central+Square+Capital+City+Ukraine.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 12,
      name: "Stop War 2",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Heart+Maidan+Nezalezhnosti+Central+Square+Capital+City+Ukraine.png.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 13,
      name: "Stop War 3",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Open+Hand+Maidan+Nezalezhnosti+central+Square+Capital+City+Ukraine.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 14,
      name: "Stop War 4",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Fists+Aerial+View+Saint+Andrew_s+Church+Andreevska+Street+Kyiv.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 15,
      name: "Stop War 5",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Flag+Aerial+View+Saint+Andrew_s+Church+Andreevska+Street+Kyiv.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 16,
      name: "Stop War 6",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Open+Hand+Aerial+View+Saint+Andrew_s+Church+Andreevska+Street+Kyiv.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 17,
      name: "Stop War 7",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Heart+Aerial+View+Saint+Andrew_s+Church+Andreevska+Street+Kyiv.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 18,
      name: "Stop War 8",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Fists+Night+View+Opera+House+Odessa.png.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 19,
      name: "Stop War 9",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Open+Hand+Night+View+Opera+House+Odessa.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 20,
      name: "Stop War 10",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Heart+Night+View+Opera+House+Odessa.png.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 21,
      name: "Stop War 11",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Never+Forget/NFTs/PNG/Flag+Night+View+Opera+House+Odessa.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Refugees",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Never Forget",
      price: "1000",
      currency: "CSPR",
      description: "We will fight back ",
    },
    {
      id: 22,
      name: "Forever Key 1",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/1.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 23,
      name: "Forever Key 2",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/2.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 24,
      name: "Forever Key 3",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/3.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 25,
      name: "Forever Key 4",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/4.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 26,
      name: "Forever Key 5",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/5.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 27,
      name: "Forever Key 6",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/6.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 28,
      name: "Forever Key 7",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/7.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 29,
      name: "Forever Key 8",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/8.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 30,
      name: "Forever Key 9",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/9.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 31,
      name: "Forever Key 10",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/10.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 32,
      name: "Forever Key 11",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/11.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 33,
      name: "Forever Key 12",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/12.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 34,
      name: "Forever Key 13",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/13.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 35,
      name: "Forever Key 14",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/14.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 36,
      name: "Forever Key 15",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/15.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 37,
      name: "Forever Key 16",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/16.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 38,
      name: "Forever Key 17",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/17.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 39,
      name: "Forever Key 18",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/18.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 40,
      name: "Forever Key 19",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/19.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 41,
      name: "Forever Key 20",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/20.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 42,
      name: "Forever Key 21",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/21.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 43,
      name: "Forever Key 22",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/22.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 44,
      name: "Forever Key 23",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/23.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 45,
      name: "Forever Key 24",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/24.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 46,
      name: "Forever Key 25",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/25.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 47,
      name: "Forever Key 26",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/26.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 48,
      name: "Forever Key 27",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/27.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 49,
      name: "Forever Key 28",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/28.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 50,
      name: "Forever Key 29",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/29.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 51,
      name: "Forever Key 30",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/Forever+Keys/Male/Z_Output/5-5-2022/30.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Reconstruction",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "Forever Keys",
      price: "1000",
      currency: "CSPR",
      description: "You may be able of kicking me out, but I hold the key to my home! Each key is had drawn with the map of Ukraine as the exact unlock. The rest watch stopped on the invasion date and time. Each NFT is unique, like the home it came from.",
    },
    {
      id: 52,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_1.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 53,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_2.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 54,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_3.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 55,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_4.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 56,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_5.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 57,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_6.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 58,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_7.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 59,
      name: "Snake Sunk",
      image:
        "https://vi-nfts-storage.s3.us-east-2.amazonaws.com/NFT+Punks/A+Hero_s+Stand/Stamp_8.png",
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "NFT Punks",
      creatorPercentage: "20",
      collection: "A Hero's Stand",
      price: "1000",
      currency: "CSPR",
      description: "Got bitten by the snake island and sank ",
    },
    {
      id: 60,
      name: "Defiant we stand",
      image:
        Bucha1,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 61,
      name: "Defiant we stand",
      image:
        Bucha2,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 62,
      name: "Defiant we stand",
      image:
        Bucha3,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 63,
      name: "Defiant we stand",
      image:
        Bucha4,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 64,
      name: "Defiant we stand",
      image:
        Bucha5,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 65,
      name: "Defiant we stand",
      image:
        Bucha6,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 66,
      name: "Defiant we stand",
      image:
        Bucha7,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 67,
      name: "Defiant we stand",
      image:
        Bucha8,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 68,
      name: "Defiant we stand",
      image:
        Bucha9,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 69,
      name: "Defiant we stand",
      image:
        Bucha10,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 70,
      name: "Defiant we stand",
      image:
        Bucha11,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    },
    {
      id: 71,
      name: "Defiant we stand",
      image:
        Bucha12,
      category: "2",
      beneficiary: "Ukraine Gov",
      beneficiaryPercentage: "80",
      campaign: "Stand With Ukraine",
      creator: "Olga Litvinenko",
      creatorPercentage: "20",
      collection: "Bucha",
      price: "1000",
      currency: "CSPR",
      description: "You can burn our homes down, but we stand defiant!",
    }
  ];